spring:
  # mysql 的配置
  config:
    name: security
    location: classpath:/config/
  datasource:
    url: jdbc:mysql://localhost:3306/sast_2022_woc?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: xz600300





server:
  port: 8080
  address: 127.0.0.1


# mybatis 的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

